
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Se7en
 */
public class Blend extends javax.swing.JFrame {

    String batch;
    String[] data;
    String[] temp;

    /**
     * Creates new form Blend
     */
    public Blend() {
        initComponents();
        Pinwheel.setBounce("blend");
        this.colTxt.setEnabled(false);
        try {
            this.colBox.setModel(new DefaultComboBoxModel(Pinwheel.getColour().toArray()));
        } catch (SQLException ex) {
            Logger.getLogger(Blend.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.colBox.addItem("Override");
        this.stageBox.setModel(new DefaultComboBoxModel(Pinwheel.getStages().toArray()));
        this.check();
        this.data = Pinwheel.getData();
        this.batch = this.data[0];
        this.selectedTxt.setText(batch);
        this.temp = Pinwheel.getTempdata();

        for (int i = 0; i < temp.length; i++) {
            if (Pinwheel.data[0].equals(temp[i])) {
                Pinwheel.setSpecTempData("", i);
            }
            for (int j = 1; j < temp.length; j++) {
                if (i != j && temp[i].equals(temp[j]) && !temp[i].equals("")) {
                    Pinwheel.setSpecTempData("", j);
                }
            }
        }
        this.batch2Txt.setText(temp[0]);
        this.batch3Txt.setText(temp[1]);
        this.batch4Txt.setText(temp[2]);
        this.batch5Txt.setText(temp[3]);
        this.batch6Txt.setText(temp[4]);
        this.batch7Txt.setText(temp[5]);
        this.batch8Txt.setText(temp[6]);
        this.batch9Txt.setText(temp[7]);

        this.refresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        selectedTxt = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        okBtn = new javax.swing.JButton();
        batch2Txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        select2Btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        select3Btn = new javax.swing.JButton();
        batch3Txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        select4Btn = new javax.swing.JButton();
        batch4Txt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        batch5Txt = new javax.swing.JTextField();
        select5Btn = new javax.swing.JButton();
        select6Btn = new javax.swing.JButton();
        select7Btn = new javax.swing.JButton();
        batch7Txt = new javax.swing.JTextField();
        batch6Txt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        batch8Txt = new javax.swing.JTextField();
        select8Btn = new javax.swing.JButton();
        select9Btn = new javax.swing.JButton();
        batch9Txt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        per1Txt = new javax.swing.JTextField();
        per2Txt = new javax.swing.JTextField();
        per4Txt = new javax.swing.JTextField();
        per7Txt = new javax.swing.JTextField();
        per5Txt = new javax.swing.JTextField();
        per6Txt = new javax.swing.JTextField();
        per8Txt = new javax.swing.JTextField();
        per9Txt = new javax.swing.JTextField();
        select1Btn = new javax.swing.JButton();
        per3Txt = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        volTxt = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        stageBox = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        colTxt = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        clear3 = new javax.swing.JButton();
        clear4 = new javax.swing.JButton();
        clear5 = new javax.swing.JButton();
        clear6 = new javax.swing.JButton();
        clear7 = new javax.swing.JButton();
        clear8 = new javax.swing.JButton();
        clear9 = new javax.swing.JButton();
        colBox = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Blend Batches");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel1.setText("Batch 1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        selectedTxt.setEditable(false);
        selectedTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectedTxtActionPerformed(evt);
            }
        });
        getContentPane().add(selectedTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 12, 91, -1));

        backBtn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 449, -1, -1));

        okBtn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        okBtn.setText("OK");
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });
        getContentPane().add(okBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(734, 449, -1, -1));

        batch2Txt.setEditable(false);
        getContentPane().add(batch2Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 53, 91, -1));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Batch 2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 56, -1, -1));

        select2Btn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        select2Btn.setText("Select");
        select2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select2BtnActionPerformed(evt);
            }
        });
        getContentPane().add(select2Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 52, -1, -1));

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Percentage");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 15, -1, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setText("Percentage");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 55, -1, -1));

        select3Btn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        select3Btn.setText("Select");
        select3Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select3BtnActionPerformed(evt);
            }
        });
        getContentPane().add(select3Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 93, -1, -1));

        batch3Txt.setEditable(false);
        getContentPane().add(batch3Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 94, 91, -1));

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setText("Batch 3");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 97, -1, -1));

        select4Btn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        select4Btn.setText("Select");
        select4Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select4BtnActionPerformed(evt);
            }
        });
        getContentPane().add(select4Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 136, -1, -1));

        batch4Txt.setEditable(false);
        getContentPane().add(batch4Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 137, 91, -1));

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel6.setText("Batch 4");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel7.setText("Batch 7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 263, -1, -1));

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel8.setText("Batch 6");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 222, -1, -1));

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel9.setText("Batch 5");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 181, -1, -1));

        batch5Txt.setEditable(false);
        getContentPane().add(batch5Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 178, 91, -1));

        select5Btn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        select5Btn.setText("Select");
        select5Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select5BtnActionPerformed(evt);
            }
        });
        getContentPane().add(select5Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 177, -1, -1));

        select6Btn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        select6Btn.setText("Select");
        select6Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select6BtnActionPerformed(evt);
            }
        });
        getContentPane().add(select6Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 218, -1, -1));

        select7Btn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        select7Btn.setText("Select");
        select7Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select7BtnActionPerformed(evt);
            }
        });
        getContentPane().add(select7Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 259, -1, -1));

        batch7Txt.setEditable(false);
        getContentPane().add(batch7Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 91, -1));

        batch6Txt.setEditable(false);
        getContentPane().add(batch6Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 219, 91, -1));

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel11.setText("Batch 9");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 345, -1, -1));

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel12.setText("Batch 8");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 304, -1, -1));

        batch8Txt.setEditable(false);
        getContentPane().add(batch8Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 301, 91, -1));

        select8Btn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        select8Btn.setText("Select");
        select8Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select8BtnActionPerformed(evt);
            }
        });
        getContentPane().add(select8Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 300, -1, -1));

        select9Btn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        select9Btn.setText("Select");
        select9Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select9BtnActionPerformed(evt);
            }
        });
        getContentPane().add(select9Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 341, -1, -1));

        batch9Txt.setEditable(false);
        getContentPane().add(batch9Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 342, 91, -1));

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel10.setText("Percentage");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 140, -1, -1));

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel13.setText("Percentage");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 181, -1, -1));

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel14.setText("Percentage");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 222, -1, -1));

        jLabel15.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel15.setText("Percentage");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 263, -1, -1));

        jLabel16.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel16.setText("Percentage");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 304, -1, -1));

        jLabel17.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel17.setText("Percentage");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 345, -1, -1));

        per1Txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                per1TxtKeyReleased(evt);
            }
        });
        getContentPane().add(per1Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 12, 50, -1));

        per2Txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                per2TxtKeyReleased(evt);
            }
        });
        getContentPane().add(per2Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 55, 50, -1));

        per4Txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                per4TxtKeyReleased(evt);
            }
        });
        getContentPane().add(per4Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 137, 50, -1));

        per7Txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                per7TxtKeyReleased(evt);
            }
        });
        getContentPane().add(per7Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 260, 50, -1));

        per5Txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                per5TxtKeyReleased(evt);
            }
        });
        getContentPane().add(per5Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 178, 50, -1));

        per6Txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                per6TxtKeyReleased(evt);
            }
        });
        getContentPane().add(per6Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 219, 50, -1));

        per8Txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                per8TxtKeyReleased(evt);
            }
        });
        getContentPane().add(per8Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 301, 50, -1));

        per9Txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                per9TxtKeyReleased(evt);
            }
        });
        getContentPane().add(per9Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 342, 50, -1));

        select1Btn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        select1Btn.setText("Select");
        select1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select1BtnActionPerformed(evt);
            }
        });
        getContentPane().add(select1Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 11, -1, -1));

        per3Txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                per3TxtKeyReleased(evt);
            }
        });
        getContentPane().add(per3Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 94, 50, -1));

        jLabel18.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel18.setText("Percentage");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 97, -1, -1));

        jLabel19.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel19.setText("Volume");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 15, -1, -1));

        volTxt.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        volTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                volTxtKeyReleased(evt);
            }
        });
        getContentPane().add(volTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(566, 12, 100, -1));

        jLabel20.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel20.setText("Stage");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 181, -1, -1));

        stageBox.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        stageBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Please Select", "Fermentation", "Pressed", "Maturation", "Blending", "Prep for Bottling", "Bottling", "Storage" }));
        stageBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stageBoxActionPerformed(evt);
            }
        });
        getContentPane().add(stageBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(561, 178, -1, -1));

        jLabel21.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel21.setText("Colour");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 97, -1, -1));

        colTxt.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        colTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                colTxtKeyReleased(evt);
            }
        });
        getContentPane().add(colTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(679, 94, 100, -1));

        jLabel22.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel22.setText("Name");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 263, -1, -1));

        nameTxt.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        nameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameTxtKeyReleased(evt);
            }
        });
        getContentPane().add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, 100, -1));

        clear3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        clear3.setText("Clear");
        clear3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear3ActionPerformed(evt);
            }
        });
        getContentPane().add(clear3, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 93, -1, -1));

        clear4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        clear4.setText("Clear");
        clear4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear4ActionPerformed(evt);
            }
        });
        getContentPane().add(clear4, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 136, -1, -1));

        clear5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        clear5.setText("Clear");
        clear5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear5ActionPerformed(evt);
            }
        });
        getContentPane().add(clear5, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 177, -1, -1));

        clear6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        clear6.setText("Clear");
        clear6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear6ActionPerformed(evt);
            }
        });
        getContentPane().add(clear6, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 218, -1, -1));

        clear7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        clear7.setText("Clear");
        clear7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear7ActionPerformed(evt);
            }
        });
        getContentPane().add(clear7, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 259, -1, -1));

        clear8.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        clear8.setText("Clear");
        clear8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear8ActionPerformed(evt);
            }
        });
        getContentPane().add(clear8, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 300, -1, -1));

        clear9.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        clear9.setText("Clear");
        clear9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear9ActionPerformed(evt);
            }
        });
        getContentPane().add(clear9, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 341, -1, -1));

        colBox.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        colBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        colBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colBoxActionPerformed(evt);
            }
        });
        getContentPane().add(colBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(566, 94, -1, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagery/WoodNew.jpg"))); // NOI18N
        jLabel24.setText("jLabel24");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        int percentcheck = Integer.parseInt(per1Txt.getText());
        
        if (batch2Txt.getText().length() > 0) {
            percentcheck += Integer.parseInt(per2Txt.getText());
        }
        if (batch3Txt.getText().length() > 0) {
            percentcheck += Integer.parseInt(per3Txt.getText());
        }
        if (batch4Txt.getText().length() > 0) {
            percentcheck += Integer.parseInt(per4Txt.getText());
        }
        if (batch5Txt.getText().length() > 0) {
            percentcheck += Integer.parseInt(per5Txt.getText());
        }
        if (batch6Txt.getText().length() > 0) {
            percentcheck += Integer.parseInt(per6Txt.getText());
        }
        if (batch7Txt.getText().length() > 0) {
            percentcheck += Integer.parseInt(per7Txt.getText());
        }
        if (batch8Txt.getText().length() > 0) {
            percentcheck += Integer.parseInt(per8Txt.getText());
        }
        if (batch9Txt.getText().length() > 0) {
            percentcheck += Integer.parseInt(per9Txt.getText());
        }
        if (percentcheck == 100) {
            double masscheck;
            boolean[] ready = new boolean[9];
            for (int i = 0; i < ready.length; i++) {
                ready[i] = false;
            }
            masscheck = Double.parseDouble(volTxt.getText()) * (Double.parseDouble(per1Txt.getText()) / 100);
            boolean mass = true;

            if (Double.parseDouble(Pinwheel.data[4]) < masscheck) {
                mass = false;
                JOptionPane.showMessageDialog(null, "Insufficient volume in batch " + selectedTxt.getText() + " to contribute " + per1Txt.getText());
            } else {
                ready[0] = true;
            }

            masscheck = Double.parseDouble(volTxt.getText()) * (Double.parseDouble(per2Txt.getText()) / 100);
            if (Double.parseDouble(Pinwheel.tempdataMass[0]) < masscheck) {
                mass = false;
                JOptionPane.showMessageDialog(null, "Insufficient volume in batch " + batch2Txt.getText() + " to contribute " + per2Txt.getText());
            } else {
                ready[1] = true;
            }

            if (batch3Txt.getText().length() > 0) {
                masscheck = Double.parseDouble(volTxt.getText()) * (Double.parseDouble(per3Txt.getText()) / 100);
                if (Double.parseDouble(Pinwheel.tempdataMass[1]) < masscheck) {
                    mass = false;
                    JOptionPane.showMessageDialog(null, "Insufficient volume in batch " + batch3Txt.getText() + " to contribute " + per3Txt.getText());
                } else {
                    ready[2] = true;
                }
                if (batch4Txt.getText().length() > 0) {
                    masscheck = Double.parseDouble(volTxt.getText()) * (Double.parseDouble(per4Txt.getText()) / 100);
                    if (Double.parseDouble(Pinwheel.tempdataMass[2]) < masscheck) {
                        mass = false;
                        JOptionPane.showMessageDialog(null, "Insufficient volume in batch " + batch4Txt.getText() + " to contribute " + per4Txt.getText());
                    } else {
                        ready[3] = true;
                    }
                    if (batch5Txt.getText().length() > 0) {
                        masscheck = Double.parseDouble(volTxt.getText()) * (Double.parseDouble(per5Txt.getText()) / 100);
                        if (Double.parseDouble(Pinwheel.tempdataMass[3]) < masscheck) {
                            mass = false;
                            JOptionPane.showMessageDialog(null, "Insufficient volume in batch " + batch5Txt.getText() + " to contribute " + per5Txt.getText());
                        } else {
                            ready[4] = true;
                        }
                        if (batch6Txt.getText().length() > 0) {
                            masscheck = Double.parseDouble(volTxt.getText()) * (Double.parseDouble(per6Txt.getText()) / 100);
                            if (Double.parseDouble(Pinwheel.tempdataMass[4]) < masscheck) {
                                mass = false;
                                JOptionPane.showMessageDialog(null, "Insufficient volume in batch " + batch6Txt.getText() + " to contribute " + per6Txt.getText());
                            } else {
                                ready[5] = true;
                            }
                            if (batch7Txt.getText().length() > 0) {
                                masscheck = Double.parseDouble(volTxt.getText()) * (Double.parseDouble(per7Txt.getText()) / 100);
                                if (Double.parseDouble(Pinwheel.tempdataMass[5]) < masscheck) {
                                    mass = false;
                                    JOptionPane.showMessageDialog(null, "Insufficient volume in batch " + batch7Txt.getText() + " to contribute " + per7Txt.getText());
                                } else {
                                    ready[6] = true;
                                }
                                if (batch8Txt.getText().length() > 0) {
                                    masscheck = Double.parseDouble(volTxt.getText()) * (Double.parseDouble(per8Txt.getText()) / 100);
                                    if (Double.parseDouble(Pinwheel.tempdataMass[6]) < masscheck) {

                                        JOptionPane.showMessageDialog(null, "Insufficient volume in batch " + batch8Txt.getText() + " to contribute " + per8Txt.getText());
                                        mass = false;
                                    } else {
                                        ready[7] = true;
                                    }
                                    if (batch9Txt.getText().length() > 0) {
                                        masscheck = Double.parseDouble(volTxt.getText()) * (Double.parseDouble(per9Txt.getText()) / 100);
                                        if (Double.parseDouble(Pinwheel.tempdataMass[7]) < masscheck) {
                                            mass = false;
                                            JOptionPane.showMessageDialog(null, "Insufficient volume in batch " + batch9Txt.getText() + " to contribute " + per9Txt.getText());
                                        } else {
                                            ready[8] = true;
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }

            if (mass) {
                String sql;
                if (ready[0]) {
                    sql = "UPDATE subbatch SET mass = mass - " + Double.parseDouble(volTxt.getText()) * (Double.parseDouble(per1Txt.getText()) / 100) + " WHERE subbatchid = '" + selectedTxt.getText() + "'";
                    Pinwheel.updateCCDB(sql);
                }
                if (ready[1]) {
                    sql = "UPDATE subbatch SET mass = mass - " + Double.parseDouble(volTxt.getText()) * (Double.parseDouble(per2Txt.getText()) / 100) + " WHERE subbatchid = '" + batch2Txt.getText() + "'";
                    Pinwheel.updateCCDB(sql);
                }
                if (ready[2]) {
                    sql = "UPDATE subbatch SET mass = mass - " + Double.parseDouble(volTxt.getText()) * (Double.parseDouble(per3Txt.getText()) / 100) + " WHERE subbatchid = '" + batch3Txt.getText() + "'";
                    Pinwheel.updateCCDB(sql);
                }
                if (ready[3]) {
                    sql = "UPDATE subbatch SET mass = mass - " + Double.parseDouble(volTxt.getText()) * (Double.parseDouble(per4Txt.getText()) / 100) + " WHERE subbatchid = '" + batch4Txt.getText() + "'";
                    Pinwheel.updateCCDB(sql);
                }
                if (ready[4]) {
                    sql = "UPDATE subbatch SET mass = mass - " + Double.parseDouble(volTxt.getText()) * (Double.parseDouble(per5Txt.getText()) / 100) + " WHERE subbatchid = '" + batch5Txt.getText() + "'";
                    Pinwheel.updateCCDB(sql);
                }
                if (ready[5]) {
                    sql = "UPDATE subbatch SET mass = mass - " + Double.parseDouble(volTxt.getText()) * (Double.parseDouble(per6Txt.getText()) / 100) + " WHERE subbatchid = '" + batch6Txt.getText() + "'";
                    Pinwheel.updateCCDB(sql);
                }
                if (ready[6]) {
                    sql = "UPDATE subbatch SET mass = mass - " + Double.parseDouble(volTxt.getText()) * (Double.parseDouble(per7Txt.getText()) / 100) + " WHERE subbatchid = '" + batch7Txt.getText() + "'";
                    Pinwheel.updateCCDB(sql);
                }
                if (ready[7]) {
                    sql = "UPDATE subbatch SET mass = mass - " + Double.parseDouble(volTxt.getText()) * (Double.parseDouble(per8Txt.getText()) / 100) + " WHERE subbatchid = '" + batch8Txt.getText() + "'";
                    Pinwheel.updateCCDB(sql);
                }
                if (ready[8]) {
                    sql = "UPDATE subbatch SET mass = mass - " + Double.parseDouble(volTxt.getText()) * (Double.parseDouble(per9Txt.getText()) / 100) + " WHERE subbatchid = '" + batch9Txt.getText() + "'";
                    Pinwheel.updateCCDB(sql);
                }

                String bid, name, colour, stage;
                int volume = Integer.parseInt(volTxt.getText());
                name = this.nameTxt.getText();
                colour = (this.colBox.getSelectedItem().equals("Override")) ? this.colTxt.getText() : this.colBox.getSelectedItem() + "";
                stage = (String) this.stageBox.getSelectedItem();

                sql = "SELECT COUNT(*) FROM blend";
                ResultSet rs;
                int id = 0;
                try {
                    rs = Pinwheel.queryCCDB(sql);
                    if (rs.next()) {
                        id = rs.getInt(1);
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Blend.class.getName()).log(Level.SEVERE, null, ex);
                }

                bid = "" + id;

                sql = "INSERT INTO blend (bid, winename, colour, volume, stage, fid1, pid1, fid2, pid2";
                if (batch3Txt.getText().length() > 0) {
                    sql += ", fid3, pid3";

                    if (batch4Txt.getText().length() > 0) {
                        sql += ", fid4, pid4";

                        if (batch5Txt.getText().length() > 0) {
                            sql += ", fid5, pid5";

                            if (batch6Txt.getText().length() > 0) {
                                sql += ", fid6, pid6";

                                if (batch7Txt.getText().length() > 0) {
                                    sql += ", fid7, pid7";
                                    if (batch8Txt.getText().length() > 0) {
                                        sql += ", fid8, pid8";
                                        if (batch9Txt.getText().length() > 0) {
                                            sql += ", fid9, pid9";
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
                sql += ") VALUES('" + bid + "', '" + name + "', '" + colour + "', '" + volume + "', '" + Pinwheel.stageGetNo(stage)
                        + "', '" + this.selectedTxt.getText() + "', '" + Integer.parseInt(this.per1Txt.getText()) + "', '" + this.batch2Txt.getText() + "', '"
                        + Integer.parseInt(this.per2Txt.getText()) + "'";

                if (batch3Txt.getText().length() > 0) {
                    sql += ", '" + this.batch3Txt.getText() + "', '" + Integer.parseInt(this.per3Txt.getText()) + "'";

                    if (batch4Txt.getText().length() > 0) {
                        sql += ", '" + this.batch4Txt.getText() + "', '" + Integer.parseInt(this.per4Txt.getText()) + "'";

                        if (batch5Txt.getText().length() > 0) {
                            sql += ", '" + this.batch5Txt.getText() + "', '" + Integer.parseInt(this.per5Txt.getText()) + "'";

                            if (batch6Txt.getText().length() > 0) {
                                sql += ", '" + this.batch6Txt.getText() + "', '" + Integer.parseInt(this.per6Txt.getText()) + "'";

                                if (batch7Txt.getText().length() > 0) {
                                    sql += ", '" + this.batch7Txt.getText() + "', '" + Integer.parseInt(this.per7Txt.getText()) + "'";

                                    if (batch8Txt.getText().length() > 0) {
                                        sql += ", '" + this.batch8Txt.getText() + "', '" + Integer.parseInt(this.per8Txt.getText()) + "'";

                                        if (batch9Txt.getText().length() > 0) {
                                            sql += ", '" + this.batch9Txt.getText() + "', '" + Integer.parseInt(this.per9Txt.getText()) + "'";
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
                sql += ")";
                Pinwheel.updateCCDB(sql);

                String ID = (bid);
                Pinwheel.createChem(ID);

                this.chem(ID, this.selectedTxt.getText(), Integer.parseInt(per1Txt.getText()));
                this.chem(ID, this.batch2Txt.getText(), Integer.parseInt(per2Txt.getText()));

                if (batch3Txt.getText().length() > 0) {
                    this.chem(ID, this.batch3Txt.getText(), Integer.parseInt(per3Txt.getText()));

                    if (batch4Txt.getText().length() > 0) {
                        this.chem(ID, this.batch4Txt.getText(), Integer.parseInt(per4Txt.getText()));

                        if (batch5Txt.getText().length() > 0) {
                            this.chem(ID, this.batch5Txt.getText(), Integer.parseInt(per5Txt.getText()));

                            if (batch6Txt.getText().length() > 0) {
                                this.chem(ID, this.batch6Txt.getText(), Integer.parseInt(per6Txt.getText()));

                                if (batch7Txt.getText().length() > 0) {
                                    this.chem(ID, this.batch7Txt.getText(), Integer.parseInt(per7Txt.getText()));

                                    if (batch8Txt.getText().length() > 0) {
                                        this.chem(ID, this.batch8Txt.getText(), Integer.parseInt(per8Txt.getText()));

                                        if (batch9Txt.getText().length() > 0) {
                                            this.chem(ID, this.batch9Txt.getText(), Integer.parseInt(per9Txt.getText()));
                                        }
                                    }
                                }
                            }
                        }
                    }
                }

            }
        } else {
            JOptionPane.showMessageDialog(null, "Total percentage does not equal 100%");
        }

    }//GEN-LAST:event_okBtnActionPerformed

    private void select2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select2BtnActionPerformed
        
        SearchBatch s = new SearchBatch(true, 0);
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_select2BtnActionPerformed

    private void select3BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select3BtnActionPerformed

        SearchBatch s = new SearchBatch(true, 1);
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_select3BtnActionPerformed

    private void select4BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select4BtnActionPerformed
      
        SearchBatch s = new SearchBatch(true, 2);
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_select4BtnActionPerformed

    private void select5BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select5BtnActionPerformed
   
        SearchBatch s = new SearchBatch(true, 3);
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_select5BtnActionPerformed

    private void select6BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select6BtnActionPerformed
       
        SearchBatch s = new SearchBatch(true, 4);
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_select6BtnActionPerformed

    private void select7BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select7BtnActionPerformed
    
        SearchBatch s = new SearchBatch(true, 5);
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_select7BtnActionPerformed

    private void select8BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select8BtnActionPerformed

        SearchBatch s = new SearchBatch(true, 6);
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_select8BtnActionPerformed

    private void select9BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select9BtnActionPerformed
      
        SearchBatch s = new SearchBatch(true, 7);
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_select9BtnActionPerformed

    private void select1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select1BtnActionPerformed
        
        SearchBatch s = new SearchBatch();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_select1BtnActionPerformed

    private void selectedTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectedTxtActionPerformed
        this.check();
    }//GEN-LAST:event_selectedTxtActionPerformed

    private void stageBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stageBoxActionPerformed
        this.check();
    }//GEN-LAST:event_stageBoxActionPerformed

    private void volTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_volTxtKeyReleased
        this.volTxt.setText(this.volTxt.getText().replaceAll("[^\\d.]", ""));
        this.check();
    }//GEN-LAST:event_volTxtKeyReleased

    private void colTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_colTxtKeyReleased
        this.check();
    }//GEN-LAST:event_colTxtKeyReleased

    private void nameTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTxtKeyReleased
        this.check();
    }//GEN-LAST:event_nameTxtKeyReleased

    private void per1TxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_per1TxtKeyReleased
        this.per1Txt.setText(this.per1Txt.getText().replaceAll("[^\\d.]", ""));
        this.check();
    }//GEN-LAST:event_per1TxtKeyReleased

    private void per2TxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_per2TxtKeyReleased
        this.per2Txt.setText(this.per2Txt.getText().replaceAll("[^\\d.]", ""));
        this.check();
    }//GEN-LAST:event_per2TxtKeyReleased

    private void per3TxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_per3TxtKeyReleased
        this.per3Txt.setText(this.per3Txt.getText().replaceAll("[^\\d.]", ""));
        this.check();
    }//GEN-LAST:event_per3TxtKeyReleased

    private void per4TxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_per4TxtKeyReleased
        this.per4Txt.setText(this.per4Txt.getText().replaceAll("[^\\d.]", ""));
        this.check();
    }//GEN-LAST:event_per4TxtKeyReleased

    private void per5TxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_per5TxtKeyReleased
        this.per5Txt.setText(this.per5Txt.getText().replaceAll("[^\\d.]", ""));
        this.check();
    }//GEN-LAST:event_per5TxtKeyReleased

    private void per6TxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_per6TxtKeyReleased
        this.per6Txt.setText(this.per6Txt.getText().replaceAll("[^\\d.]", ""));
        this.check();
    }//GEN-LAST:event_per6TxtKeyReleased

    private void per7TxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_per7TxtKeyReleased
        this.per7Txt.setText(this.per7Txt.getText().replaceAll("[^\\d.]", ""));
        this.check();
    }//GEN-LAST:event_per7TxtKeyReleased

    private void per8TxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_per8TxtKeyReleased
        this.per8Txt.setText(this.per8Txt.getText().replaceAll("[^\\d.]", ""));
        this.check();
    }//GEN-LAST:event_per8TxtKeyReleased

    private void per9TxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_per9TxtKeyReleased
        this.per9Txt.setText(this.per9Txt.getText().replaceAll("[^\\d.]", ""));
        this.check();
    }//GEN-LAST:event_per9TxtKeyReleased

    private void clear3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear3ActionPerformed
        this.temp[1] = "";
        this.per3Txt.setText("");
        this.batch3Txt.setText("");

        this.clear4.doClick();

    }//GEN-LAST:event_clear3ActionPerformed

    private void clear4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear4ActionPerformed
        this.temp[2] = "";
        this.per4Txt.setText("");
        this.batch4Txt.setText("");
        this.clear5.doClick();
    }//GEN-LAST:event_clear4ActionPerformed

    private void clear5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear5ActionPerformed
        this.temp[3] = "";
        this.per5Txt.setText("");
        this.batch5Txt.setText("");
        this.clear6.doClick();
    }//GEN-LAST:event_clear5ActionPerformed

    private void clear6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear6ActionPerformed
        this.temp[4] = "";
        this.per6Txt.setText("");
        this.batch6Txt.setText("");
        this.clear7.doClick();
    }//GEN-LAST:event_clear6ActionPerformed

    private void clear7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear7ActionPerformed
        this.temp[5] = "";
        this.per7Txt.setText("");
        this.batch7Txt.setText("");
        this.clear8.doClick();
    }//GEN-LAST:event_clear7ActionPerformed

    private void clear8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear8ActionPerformed
        this.temp[6] = "";
        this.per8Txt.setText("");
        this.batch8Txt.setText("");
        this.clear9.doClick();
    }//GEN-LAST:event_clear8ActionPerformed

    private void clear9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear9ActionPerformed
        this.temp[7] = "";
        this.per9Txt.setText("");
        Pinwheel.setTempData(temp);
        this.batch9Txt.setText("");
        this.refresh();
    }//GEN-LAST:event_clear9ActionPerformed

    private void colBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colBoxActionPerformed
        if (colBox.getSelectedItem().equals("Override")) {
            colTxt.setEnabled(true);
        } else {
            colTxt.setEnabled(false);
        }
    }//GEN-LAST:event_colBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField batch2Txt;
    private javax.swing.JTextField batch3Txt;
    private javax.swing.JTextField batch4Txt;
    private javax.swing.JTextField batch5Txt;
    private javax.swing.JTextField batch6Txt;
    private javax.swing.JTextField batch7Txt;
    private javax.swing.JTextField batch8Txt;
    private javax.swing.JTextField batch9Txt;
    private javax.swing.JButton clear3;
    private javax.swing.JButton clear4;
    private javax.swing.JButton clear5;
    private javax.swing.JButton clear6;
    private javax.swing.JButton clear7;
    private javax.swing.JButton clear8;
    private javax.swing.JButton clear9;
    private javax.swing.JComboBox colBox;
    private javax.swing.JTextField colTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JButton okBtn;
    private javax.swing.JTextField per1Txt;
    private javax.swing.JTextField per2Txt;
    private javax.swing.JTextField per3Txt;
    private javax.swing.JTextField per4Txt;
    private javax.swing.JTextField per5Txt;
    private javax.swing.JTextField per6Txt;
    private javax.swing.JTextField per7Txt;
    private javax.swing.JTextField per8Txt;
    private javax.swing.JTextField per9Txt;
    private javax.swing.JButton select1Btn;
    private javax.swing.JButton select2Btn;
    private javax.swing.JButton select3Btn;
    private javax.swing.JButton select4Btn;
    private javax.swing.JButton select5Btn;
    private javax.swing.JButton select6Btn;
    private javax.swing.JButton select7Btn;
    private javax.swing.JButton select8Btn;
    private javax.swing.JButton select9Btn;
    private javax.swing.JTextField selectedTxt;
    private javax.swing.JComboBox stageBox;
    private javax.swing.JTextField volTxt;
    // End of variables declaration//GEN-END:variables

    private void check() {
        okBtn.setEnabled(false);
        System.out.println("check");
        if (selectedTxt.getText().length() > 0 && batch2Txt.getText().length() > 0 && volTxt.getText().length() > 0 && (colTxt.getText().length() > 0 || !colBox.getSelectedItem().equals("Override")) && nameTxt.getText().length() > 0) {
            if (!per1Txt.isEnabled() || !per1Txt.getText().isEmpty()) {
                if (!per2Txt.isEnabled() || !per2Txt.getText().isEmpty()) {
                    if (!per3Txt.isEnabled() || !per3Txt.getText().isEmpty()) {
                        if (!per4Txt.isEnabled() || !per4Txt.getText().isEmpty()) {
                            if (!per5Txt.isEnabled() || !per5Txt.getText().isEmpty()) {
                                if (!per6Txt.isEnabled() || !per6Txt.getText().isEmpty()) {
                                    if (!per7Txt.isEnabled() || !per7Txt.getText().isEmpty()) {
                                        if (!per8Txt.isEnabled() || !per8Txt.getText().isEmpty()) {
                                            if (!per9Txt.isEnabled() || !per9Txt.getText().isEmpty()) {
                                                okBtn.setEnabled(true);
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    private void refresh() {
        this.select3Btn.setEnabled(false);
        this.select4Btn.setEnabled(false);
        this.select5Btn.setEnabled(false);
        this.select6Btn.setEnabled(false);
        this.select7Btn.setEnabled(false);
        this.select8Btn.setEnabled(false);
        this.select9Btn.setEnabled(false);

        this.per2Txt.setEnabled(false);
        this.per3Txt.setEnabled(false);
        this.per4Txt.setEnabled(false);
        this.per5Txt.setEnabled(false);
        this.per6Txt.setEnabled(false);
        this.per7Txt.setEnabled(false);
        this.per8Txt.setEnabled(false);
        this.per9Txt.setEnabled(false);

        if (batch2Txt.getText().length() > 0) {
            this.select3Btn.setEnabled(true);
            this.per2Txt.setEnabled(true);
            if (batch3Txt.getText().length() > 0) {
                this.select4Btn.setEnabled(true);
                this.per3Txt.setEnabled(true);
                if (batch4Txt.getText().length() > 0) {
                    this.select5Btn.setEnabled(true);
                    this.per4Txt.setEnabled(true);
                    if (batch5Txt.getText().length() > 0) {
                        this.select6Btn.setEnabled(true);
                        this.per5Txt.setEnabled(true);
                        if (batch6Txt.getText().length() > 0) {
                            this.select7Btn.setEnabled(true);
                            this.per6Txt.setEnabled(true);
                            if (batch7Txt.getText().length() > 0) {
                                this.select8Btn.setEnabled(true);
                                this.per7Txt.setEnabled(true);
                                if (batch8Txt.getText().length() > 0) {
                                    this.select9Btn.setEnabled(true);
                                    this.per8Txt.setEnabled(true);
                                    if (batch9Txt.getText().length() > 0) {
                                        this.per9Txt.setEnabled(true);
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    private void chem(String bid, String batch, double percent) {
        String sql = "SELECT * FROM " + batch;
        System.out.println(batch);
        double amount;
        try {
            ResultSet rs = Pinwheel.queryChem(sql);
            while (rs.next()) {
                String chem = rs.getNString(1);
                amount = rs.getInt(2);
                
                double newamount = amount * ((percent / Double.parseDouble(this.volTxt.getText()))*100);
                Pinwheel.insertCustomChemicalAt(bid, chem, newamount + "");
                Pinwheel.insertCustomChemicalAt(batch, chem, -newamount + "");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Blend.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
