/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Se7en
 */
public class Prompt extends javax.swing.JFrame {

    String data[];

    /**
     * Creates new form Prompt
     */
    public Prompt() {
        initComponents();
        this.data = Pinwheel.getData();

        this.txtLbl.setText("<html>" + this.txtLbl.getText() + "<br/>ID:" + this.data[0] + "</html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtLbl = new javax.swing.JLabel();
        promptTxt = new javax.swing.JTextField();
        okBtn = new javax.swing.JButton();
        idLbl = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("APPROVE?");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtLbl.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtLbl.setText("Please enter the ID of the batch you are trying to edit/delete");
        getContentPane().add(txtLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 10, -1, -1));

        promptTxt.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        promptTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                promptTxtKeyReleased(evt);
            }
        });
        getContentPane().add(promptTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 72, 333, 30));

        okBtn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        okBtn.setText("OK");
        okBtn.setEnabled(false);
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });
        getContentPane().add(okBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 110, -1, -1));
        getContentPane().add(idLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 31, 99, 57));

        cancelBtn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        getContentPane().add(cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

<<<<<<< HEAD
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagery/WoodNew.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 160));
=======
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(promptTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cancelBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(okBtn)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtLbl))
                .addContainerGap(40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(idLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(promptTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cancelBtn)
                            .addComponent(okBtn))
                        .addGap(27, 27, 27))))
        );
>>>>>>> refs/remotes/origin/master

        setSize(new java.awt.Dimension(366, 199));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void promptTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_promptTxtKeyReleased
        if (this.promptTxt.getText().equals(this.data[0])) {
            this.okBtn.setEnabled(true);
        } else {
            this.okBtn.setEnabled(false);
        }
    }//GEN-LAST:event_promptTxtKeyReleased

    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        switch (Pinwheel.getBounce()) {
            case "edit":
                switch (Pinwheel.getSearchType()) {
                    case "batch":
                        Pinwheel.deleteBatch();
                        Pinwheel.insertBatch();
                        break;
                    case "supplier":
                        Pinwheel.deleteSupplier();
                        Pinwheel.insertSupplier();
                        break;
                    case "chemical":
                        Pinwheel.deleteChemical();
                        Pinwheel.insertChemical();
                        break;
                }
            case "delete":
                switch (Pinwheel.getSearchType()) {
                    case "batch":
                        Pinwheel.deleteBatch();
                        break;
                    case "subbatch":
                        Pinwheel.deleteSubBatch();
                        break;
                    case "blend":
                        Pinwheel.deleteBlend();
                        break;
                    case "supplier":
                        Pinwheel.deleteSupplier();
                        break;
                    case "chemical":
                        Pinwheel.deleteChemical();
                }
        }
        this.dispose();
    }//GEN-LAST:event_okBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel idLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton okBtn;
    private javax.swing.JTextField promptTxt;
    private javax.swing.JLabel txtLbl;
    // End of variables declaration//GEN-END:variables
}
