
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Se7en
 */
public class SearchBatch extends javax.swing.JFrame {

    /**
     * Creates new form SearchBatch
     */
    String batchid;
    String colour;
    String type;
    String stage;
    boolean temp = false;
    String[] data;

    /**
     * Creates new form main
     */
    public SearchBatch() {
        
        initComponents();

        switch (Pinwheel.getSearchType()) {
            case "batch":
                this.colourBox.setModel(new DefaultComboBoxModel(Pinwheel.getColourAll().toArray()));
                this.typeBox.setModel(new DefaultComboBoxModel(Pinwheel.getTypeAll().toArray()));
                data = new String[5];
                break;
            case "supplier":
                batchTbl.getColumnModel().getColumn(0).setHeaderValue("Supplier name");
                batchTbl.getColumnModel().getColumn(1).setHeaderValue("Contact No");
                batchTbl.getColumnModel().getColumn(2).setHeaderValue("Email");
                batchTbl.getColumnModel().getColumn(3).setHeaderValue("Contact Liason");
                batchTbl.getColumnModel().removeColumn(batchTbl.getColumnModel().getColumn(4));

                data = new String[4];

                this.batchLbl.setText("Supplier Name");
                this.colourLbl.setText("");
                this.typeLbl.setText("");
                this.stageLbl.setText("");

                this.stageBox.setVisible(false);
                this.colourBox.setVisible(false);
                this.typeBox.setVisible(false);

                this.stageBox.setEnabled(false);
                this.colourBox.setEnabled(false);
                this.typeBox.setEnabled(false);
                break;
            case "chemical":
                batchTbl.getColumnModel().getColumn(0).setHeaderValue("Chemical");
                batchTbl.getColumnModel().getColumn(1).setHeaderValue("Value");
                batchTbl.getColumnModel().removeColumn(batchTbl.getColumnModel().getColumn(2));
                batchTbl.getColumnModel().removeColumn(batchTbl.getColumnModel().getColumn(2));
                batchTbl.getColumnModel().removeColumn(batchTbl.getColumnModel().getColumn(2));

                data = new String[2];

                this.batchLbl.setText("Chemical Name");
                this.colourLbl.setText("");
                this.typeLbl.setText("");
                this.stageLbl.setText("");

                this.stageBox.setVisible(false);
                this.colourBox.setVisible(false);
                this.typeBox.setVisible(false);

                this.stageBox.setEnabled(false);
                this.colourBox.setEnabled(false);
                this.typeBox.setEnabled(false);
                break;
        }
    }
    public SearchBatch(boolean a) {
        
        initComponents();
        
        temp = a;
                this.colourBox.setModel(new DefaultComboBoxModel(Pinwheel.getColourAll().toArray()));
                this.typeBox.setModel(new DefaultComboBoxModel(Pinwheel.getTypeAll().toArray()));
                data = new String[5];
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        batchTbl = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        exitBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        selectBtn = new javax.swing.JButton();
        stageBox = new javax.swing.JComboBox();
        typeBox = new javax.swing.JComboBox();
        colourBox = new javax.swing.JComboBox();
        batchIdTxt = new javax.swing.JTextField();
        batchLbl = new javax.swing.JLabel();
        colourLbl = new javax.swing.JLabel();
        typeLbl = new javax.swing.JLabel();
        stageLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel6.setText("Wine Type");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 270));

        batchTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Batch ID", "Colour", "Type", "Stage", "Mass"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        batchTbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        batchTbl.getTableHeader().setReorderingAllowed(false);
        batchTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                batchTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(batchTbl);

        jPanel2.setOpaque(false);

        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        selectBtn.setText("Select");
        selectBtn.setEnabled(false);
        selectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectBtnActionPerformed(evt);
            }
        });

        stageBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "Fermentation", "Pressed", "Maturation", "Blending", "Prep for Bottling", "Bottling", "Storage" }));

        typeBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        colourBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        batchLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        batchLbl.setText("Batch ID");

        colourLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        colourLbl.setText("Wine Colour");

        typeLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        typeLbl.setText("Wine Type");

        stageLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stageLbl.setText("Stage");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(batchLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(batchIdTxt)
                        .addGap(4, 4, 4)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(colourBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(colourLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(typeBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(typeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(stageLbl))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(stageBox, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exitBtn)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(colourLbl)
                    .addComponent(typeLbl)
                    .addComponent(stageLbl)
                    .addComponent(batchLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitBtn)
                    .addComponent(searchBtn)
                    .addComponent(selectBtn)
                    .addComponent(stageBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colourBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(batchIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 650, 300);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagery/WoodNew.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 700, 310);

        setSize(new java.awt.Dimension(663, 345));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitBtnActionPerformed

    private void selectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectBtnActionPerformed

        for (int i = 0; i < data.length; i++) {
            data[i] = (String) this.batchTbl.getValueAt(this.batchTbl.getSelectedRow(), i);
        }
        if (this.temp) {
            Pinwheel.setTempData(data);
        } else {
            Pinwheel.setData(data);
        }
        switch (Pinwheel.getBounce()) {
            case "mainsearch":
                Edit ed = new Edit();
                ed.setVisible(true);
                this.dispose();
                break;
            case "delete":
                Prompt p = new Prompt();
                p.setVisible(true);
                this.dispose();
                break;
            case "edit":
                AdminEdit ae = new AdminEdit();
                ae.setVisible(true);
                this.dispose();
                break;
            case "blend":
                Blend b = new Blend();
                b.setVisible(true);
                this.dispose();
        }
    }//GEN-LAST:event_selectBtnActionPerformed

    private void batchTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_batchTblMouseClicked
        if (batchTbl.getSelectedRow() != -1) {
            this.selectBtn.setEnabled(true);
        }
    }//GEN-LAST:event_batchTblMouseClicked

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        this.selectBtn.setEnabled(false);
        DefaultTableModel model = (DefaultTableModel) this.batchTbl.getModel();
        model.setRowCount(0);
        ResultSet rs;
        String sql;

        this.batchid = this.batchIdTxt.getText();
        this.colour = this.colourBox.getSelectedItem().toString();
        this.type = this.typeBox.getSelectedItem().toString();
        this.stage = this.stageBox.getSelectedItem().toString();
        boolean batch = !this.batchid.equals("");
        boolean col = !this.colour.equals("All");
        boolean wtype = !this.type.equals("All");
        boolean wstage = !this.stage.equals("All");
        boolean whered = false;
        sql = "";
        Object[] list;

        switch (Pinwheel.getSearchType()) {
            case "batch":
                sql = "SELECT batchid, colour, type, stage, mass FROM batch";
                list = new Object[5];
                if (batch || col || wtype || wstage) {
                    sql += " WHERE ";
                }
                if (batch) {
                    if (whered) {
                        sql += " AND ";
                    }
                    whered = true;
                    sql += " batchid LIKE '*" + this.batchid + "*'";
                }
                if (col) {
                    if (whered) {
                        sql += " AND ";
                    }
                    whered = true;
                    sql += " colour = '" + this.colour + "'";
                }
                if (wtype) {
                    if (whered) {
                        sql += " AND ";
                    }
                    whered = true;
                    sql += " type = '" + this.type + "'";
                }
                if (wstage) {
                    if (whered) {
                        sql += " AND ";
                    }
                    sql += " stage = '" + Pinwheel.stageGetNo(this.stage) + "'";
                }
                try {
                    rs = Pinwheel.queryCCDB(sql);
                    int count = 0;
                    while (rs.next()) {

                        for (int i = 0; i < list.length; i++) {
                            list[i] = (rs.getString(i + 1));
                        }
                        list[3] = Pinwheel.stageGetWord(list[3] + "");
                        ((DefaultTableModel) this.batchTbl.getModel()).insertRow(count, list);
                        count++;
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(SearchBatch.class.getName()).log(Level.SEVERE, null, ex);
                }
                break;
            case "supplier":
                sql = "SELECT sname, tel, email, liason FROM supplier";
                list = new Object[4];
                if (batch) {
                    sql += "WHERE sname = '" + this.batchid + "'";
                }
                try {
                    rs = Pinwheel.queryCCDB(sql);
                    int count = 0;
                    while (rs.next()) {

                        for (int i = 0; i < list.length; i++) {
                            list[i] = (rs.getString(i + 1));
                        }

                        ((DefaultTableModel) this.batchTbl.getModel()).insertRow(count, list);
                        count++;
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(SearchBatch.class.getName()).log(Level.SEVERE, null, ex);
                }
                break;
            case "chemical":
                sql = "SELECT chemical, value FROM chemicaltbl";
                list = new Object[2];
                if (batch) {
                    sql += "WHERE chemical = '" + this.batchid + "'";
                }
                try {
                    rs = Pinwheel.queryChem(sql);
                    int count = 0;
                    while (rs.next()) {

                        for (int i = 0; i < list.length; i++) {
                            list[i] = (rs.getString(i + 1));
                        }

                        ((DefaultTableModel) this.batchTbl.getModel()).insertRow(count, list);
                        count++;
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(SearchBatch.class.getName()).log(Level.SEVERE, null, ex);
                }
                break;
        }


    }//GEN-LAST:event_searchBtnActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField batchIdTxt;
    private javax.swing.JLabel batchLbl;
    private javax.swing.JTable batchTbl;
    private javax.swing.JComboBox colourBox;
    private javax.swing.JLabel colourLbl;
    private javax.swing.JButton exitBtn;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton selectBtn;
    private javax.swing.JComboBox stageBox;
    private javax.swing.JLabel stageLbl;
    private javax.swing.JComboBox typeBox;
    private javax.swing.JLabel typeLbl;
    // End of variables declaration//GEN-END:variables
}
