
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Se7en
 */
public class UpdateGraph extends javax.swing.JFrame {

    String batch;
    String[] batchData = new String[7];
    GraphUI gee;

    /**
     * Creates new form UpdateGraph
     */
    public UpdateGraph() {
        initComponents();
        batchData = Pinwheel.getData();
        this.batch = batchData[0];
        idTxt.setText(batch);
    }

    public UpdateGraph(GraphUI gee) {
        initComponents();
        this.gee = gee;
        batchData = Pinwheel.getData();
        this.batch = batchData[0];
        idTxt.setText(batch);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tempTxt = new javax.swing.JTextField();
        balTxt = new javax.swing.JTextField();
        okBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Update Graph");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel1.setText("Selected Batch:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, -1));

        idTxt.setEditable(false);
        idTxt.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        getContentPane().add(idTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 11, 180, -1));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Temperature:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Balling:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 138, -1, -1));

        tempTxt.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        tempTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tempTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tempTxtKeyReleased(evt);
            }
        });
        getContentPane().add(tempTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 97, 175, -1));

        balTxt.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        balTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                balTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                balTxtKeyReleased(evt);
            }
        });
        getContentPane().add(balTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 138, 175, -1));

        okBtn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        okBtn.setText("OK");
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });
        getContentPane().add(okBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 253, -1, -1));

        backBtn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 253, -1, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagery/WoodNew.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 290));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        GraphUI g = new GraphUI();
        g.setVisible(true);
        gee.kill();
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        GraphUI g = new GraphUI();
        double temp = 0, sugar = 0;
        String date;

        date = LocalDate.now(ZoneId.of("Africa/Harare")) + "";
        System.out.println("Current date " + date);

        if (!tempTxt.getText().isEmpty()) {
            temp = Double.parseDouble(tempTxt.getText());
            if (!balTxt.getText().isEmpty()) {
                sugar = Double.parseDouble(balTxt.getText());
                try {
                    Pinwheel.insertGraphAt(date, sugar, temp);
                    gee.kill();
                    g.refesh();
                    this.dispose();
                } catch (SQLException ex) {
                    Logger.getLogger(UpdateGraph.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_okBtnActionPerformed

    private void tempTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tempTxtKeyReleased
        this.tempTxt.setText(this.tempTxt.getText().replaceAll("[^\\d.]", ""));
    }//GEN-LAST:event_tempTxtKeyReleased

    private void tempTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tempTxtKeyPressed
        this.tempTxt.setText(this.tempTxt.getText().replaceAll("[^\\d.]", ""));
    }//GEN-LAST:event_tempTxtKeyPressed

    private void balTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_balTxtKeyPressed
        this.balTxt.setText(this.balTxt.getText().replaceAll("[^\\d.]", ""));
    }//GEN-LAST:event_balTxtKeyPressed

    private void balTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_balTxtKeyReleased
        this.balTxt.setText(this.balTxt.getText().replaceAll("[^\\d.]", ""));
    }//GEN-LAST:event_balTxtKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateGraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateGraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateGraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateGraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateGraph().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField balTxt;
    private javax.swing.JTextField idTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton okBtn;
    private javax.swing.JTextField tempTxt;
    // End of variables declaration//GEN-END:variables
}
